/*
 * Copyright 2026 Kevin Henry
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.javalaboratories.core.json.events;

import org.javalaboratories.core.event.EventSubscriber;

/**
 * Inherit this class to subscribe to events generated by the {@link
 * org.javalaboratories.core.json.JsonTransformer} objects.
 * <p>
 * It is not necessary for the {@code JsonTransformer} to publish events, but
 * this should be clearly documented by the transformer object: in such cases,
 * the subscriber methods are unsupported operations.
 * <p>
 * However, for {@code JsonTransformer} that do publish events, implement
 * this abstract class then register it with the subscriber method of the
 * {@code JsonTransformer} object.
 *
 * @see TransformerEvent
 * @see BeforeTransformationEvent
 * @see AfterTransformationEvent*
 */
public abstract class AbstractJsonTransformerSubscriber implements EventSubscriber<TransformerEvent> {}
