package org.javalaboratories.core.json.events;

import org.javalaboratories.core.event.EventSubscriber;

/**
 * Implement this interface to subscribe to events generated by the {@link
 * org.javalaboratories.core.json.JsonTransformer} objects.
 * <p>
 * It is not necessary for the {@code JsonTransformer} to publish events, but
 * this should be clearly documented by the transformer object: in such cases,
 * the subscriber methods are unsupported operations.
 * <p>
 * However, for {@code JsonTransformer} objects that do publish events, implement
 * this abstract class then register it with the subscriber method of the
 * {@code JsonTransformer} object.
 *
 * @see TransformerEvent
 * @see BeforeTransformationEvent
 * @see AfterTransformationEvent
 */
@FunctionalInterface
public interface JsonTransformerSubscriber extends EventSubscriber<TransformerEvent> {}
